# Generated by Django 4.0.6 on 2022-08-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goalcategory_board'),
        ('bot', '0002_tguser_verification_code_alter_tguser_tg_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='active_board',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.board', verbose_name='Поле доски для создания категории'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='active_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory', verbose_name='Поле категории для создания цели'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='bot_condition',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ожидание названия доски'), (2, 'Ожидание названия категории'), (3, 'Ожидание названия цели'), (4, 'Начало')], default=4, verbose_name='Состояние бота'),
        ),
    ]
